spring:
  application:
    name: ratelimiter

  datasource:
    url: jdbc:h2:mem:AccountDB
    driver-class-name: org.h2.Driver
    username: sa
    password: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      ertan.limit-for-period: 3
      ertan.limit-refresh-period: 1m
      ertan.timeout-duration: 2s


